config/routes.rb
ListenLater::Application.routes.draw do

  resources :series do
    resources :subscriptions, only: :create
    resources :sources, only: [:index, :show]
  end

  resources :categories, only: [:show, :index]
  resources :listens, only: [:create, :show]


  match '/', :controller => :pages, :action => :home
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    delete '/users/disconnect/:provider',
      :to => 'users#disconnect_omniauth_provider',
      :as => 'disconnect_omniauth_provider'
  end

  match 'welcome' => "users#welcome"

  match 'bookmarklet' => "users#bookmarklet"
  post 'bookmark', :controller => :sources, :action => :create

  resources :sources do
    collection do
      get 'recent'
      get 'popular'
    end
  end

  resources :subscriptions do
    resources :sources
  end

  resources :users do
    resources :sources
    resources :subscriptions
  end

  resources :tags, only: [:show, :index]


  root :to => 'pages#home'

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/source.rb
class Source < ActiveRecord::Base

  attr_accessible :title, :url

  belongs_to :series
  has_many :subscriptions, :through => :series
  has_many :users, :through => :subscriptions

  has_many :listens
  has_many :listeners, :through => :listens, :source => :user

  acts_as_taggable

  extend FriendlyId
  friendly_id :title, use: :slugged


  scope :popular, :limit => 30
  scope :suggested, :limit => 30
  scope :recent, :limit => 30
  scope :ordered, :order => "created_at DESC"
  scope :unlistened
  scope :listened, lambda{ joins(:listens) }

  def state_classes
    class_array = []
    class_array << 'listened' if listened?
    class_array
  end

  def mark_as_listened
    self.listened ||= true
    save if listened_changed?
  end

  def listened
    listens.all.size > 0
  end

  def subscription_title
    subscription ? subscription.title : self.created_at.to_s(:long)
  end

  def image_url
    series.try(:image_url) || default_image_url
  end

  def default_image_url
    'series/default.gif'
  end

  def series_title
    series.try(:title)
  end

end

app/controllers/sources_controller.rb
class SourcesController < ApplicationController

  respond_to :json, :html

  def recent
    collection = current_user ? current_user.sources : Source
    @sources = collection.recent.ordered.paginate(:page => params[:page] || 1, :per_page => 20)
    respond_with @sources
  end

  def popular
    collection = current_user ? current_user.sources : Source
    @sources = collection.popular.ordered.includes(:subscription).paginate(:page => params[:page] || 1, :per_page => 20)
    respond_with @sources
  end

  def suggested
    @sources = current_user.suggested_sources.paginate(:page => params[:page] || 1, :per_page => 20)
    respond_with @sources
  end

  def index
    @series = Series.find(params[:series_id]) if params[:series_id].present?
    @subscription = Subscription.find(params[:subscription_id]) if params[:subscription_id].present?
    collection = @subscription.sources if @subscription
    collection ||= @series.sources if @series
    collection ||= Source
    collection = collection.where(state: params[:filter]) if params[:filter]
    collection = collection.order("id DESC")
    @sources = collection.includes(:subscription).paginate(:page => params[:page] || 1, :per_page => params[:per_page] || 20)
    respond_with @sources
  end

  def show
    @source = Source.find(params[:id])
    source_base = Series.find(params[:series_id]).sources if params[:series_id]
    source_base ||= current_user.try(:sources) || Source
    @sources = source_base
                     .ordered
                     .paginate(:page => page, :per_page => per_page)
    respond_with @source
  end

  def new
    @source = Source.new
  end

  def create
    if current_user
      @source = current_user.sources.find_or_create_by_title_and_url(params[:source][:title],  params[:source][:url])
    else
      @source = Source.find_or_create_by_title_and_url(params[:source][:title],  params[:source][:url])
    end

    if params[:subscription].present?
      if subscription = Subscription.find(params[:subscription_id])
        @source.subscription = subscription
        @source.user = subscription.user
      end
    end
    @source.save!
    respond_with @source
  end

  def edit
    @source = Source.find(params[:id])
  end

  def update
    @source = Source.find(params[:id])
    if @source.update_attributes(params[:source])
      redirect_to @source
    else
      render :template => 'new'
    end
  end

end

app/helpers/sources_helper.rb
module SourcesHelper
  def bookmarklet
    render 'users/bookmarklet'
  end
end

app/views/sources/_filters.erb
<div class="button-group">
  <a class="button <%= 'active' unless params[:state].present? %>" href="?">All</a>
  <a class="button <%= 'active' if params[:state] == 'new' %>" href="?state=new">New</a>
  <a class="button <%= 'active' if params[:state] == 'listening' %>" href="?state=listening">Listening</a>
  <a class="button <%= 'active' if params[:state] == 'listened' %>" href="?state=listened">Listened</a>
  <a class="button <%= 'active' if params[:state] == 'starred' %>" href="?state=starred">Starred</a>
</div>

app/views/sources/_filters.html.erb
<div class="button-group">
  <a class="button <%= 'active' unless params[:state].present? %>" href="?">All</a>
  <a class="button <%= 'active' if params[:state] == 'new' %>" href="?state=new">New</a>
  <a class="button <%= 'active' if params[:state] == 'listening' %>" href="?state=listening">Listening</a>
  <a class="button <%= 'active' if params[:state] == 'listened' %>" href="?state=listened">Listened</a>
  <a class="button <%= 'active' if params[:state] == 'starred' %>" href="?state=starred">Starred</a>
</div>

app/views/sources/_form.haml
= simple_form_for @source, :html => {:class => 'form-horizontal' } do |form|
  = form.input :title
  = form.input :url
  .btn-group
    = form.button :submit, :class => "btn-primary"
    = link_to "Cancel", :back, :class => "btn"

  = text_area_tag 'bookmarklet', bookmarklet

app/views/sources/_nav.html.haml
%ul.nav.nav-list.source-list
  %li
    = link_to recent_sources_path do
      %i.icon-book
      Recent 
  %li
    = link_to popular_sources_path do
      %i.icon-star
      Popular
  %li
    = link_to suggested_sources_path do
      %i.icon-ok-sign
      Suggested

app/views/sources/_source.erb
<li class="source <%= source.state_classes.join(' ') %>" rel="<%= url_for(source) %>" data-image="<%= source.subscription_image_url %>" data-source-id="<%= source.id %>" data-user-id="<%= active_user.id %>">
  <%= link_to source do %>
    <div class="subscription-image">
      <%= link_to image_tag(source.subscription_image_url), source %>
    </div>
    <div class="source-details">
      <h3 class="subscription-title">
        <%= link_to source.subscription_title, subscription_sources_path(source.subscription) if source.subscription %>
        <%= source.subscription_title unless source.subscription %>
      </h3>
      <h2 class="source-title">
        <%= link_to source.title, source %>
      </h2>
      <span class="timeago" title="<%= source.created_at %>">
        <%= source.created_at.to_s(:long) %>
      </span>
    </div>
  <% end %>
</li>

app/views/sources/_source.html.erb
<%- source_link = series_source_path(@series, source) if @series %>
<%- source_link ||= source_path(source) %>
<li class="source <%= source.state_classes.join(' ') %> <%= 'current' if source == @source %>" rel="<%= url_for(source) %>" data-image="<%= source.image_url %>" data-source-id="<%= source.id %>" data-user-id="<%= active_user.id %>">
    <div class="subscription-image">
      <%= link_to(image_tag(source.image_url), source_link) %>
    </div>
    <div class="source-body">
      <h3 class="subscription-title">
        <%= link_to source.series_title, series_sources_path(source.series) if source.series%>
        <%= source.created_at unless source.series %>
      </h3>
      <h2 class="source-title">
        <%= link_to source.title, source_link %>
      </h2>
      <span class="timeago" title="<%= source.created_at %>">
        <%= source.created_at.to_s(:long) %>
      </span>
    </div>
</li>

app/views/sources/edit.haml
.hero-unit
  %h1 Edit Source
  %p A source is basically a link to an audio file with a title
= render 'sources/form'

app/views/sources/index.haml
= render 'series/detail' if @series
= render 'subscriptions/detail' if @subscription

%ul.playlist
  = render @sources

= will_paginate @sources

app/views/sources/index.html.haml
= render 'series/detail' if @series
= render 'subscriptions/detail' if @subscription

%ul.playlist
  = render @sources

= will_paginate @sources

app/views/sources/new.haml
.hero-unit
  %h1 New Source
  %p A source is basically a link to an audio file with a title
= simple_form_for :source, :html => {:class => 'form-horizontal' } do |form|
  = form.input :title
  = form.input :url
  = form.input :subscription
  .btn-group
    = form.button :submit, :class => "btn-primary"
    = link_to "Cancel", :back, :class => "btn"

app/views/sources/popular.haml
.hero-unit
  %h1 Popular
  %p Power to the people. Survival of the listened.

%ul.playlist
  = render @sources

= will_paginate @sources

app/views/sources/recent.haml
.hero-unit
  %h1 Recent
  %p Up to the minute listing of recent sources

%ul.playlist
  = render @sources

= will_paginate @sources

app/views/sources/show.haml
- content_for :page_title do
  = @source.series.title
  = ' | '
  = @source.title

.player{style: "background-image: url('/assets/#{@source.image_url}');"}
  = link_to '', @source.url, :class => 'play'
  .title
    - if @source.series
      %b
        = link_to @source.series.title, series_sources_path(@source.series)
        = "Untitled" if @source.series.title.blank?
      %span= @source.title
    - else
      %b= @source.title

%ul.playlist
  = render @sources
= will_paginate @sources

app/views/sources/suggested.haml
.hero-unit
  %h1 Suggested
  %p Things you may like.

%ul.playlist
  = render @sources

= will_paginate @sources