config/routes.rb
ListenLater::Application.routes.draw do

  resources :series do
    resources :subscriptions, only: :create
    resources :sources, only: [:index, :show]
  end

  resources :categories, only: [:show, :index]
  resources :listens, only: [:create, :show]


  match '/', :controller => :pages, :action => :home
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    delete '/users/disconnect/:provider',
      :to => 'users#disconnect_omniauth_provider',
      :as => 'disconnect_omniauth_provider'
  end

  match 'welcome' => "users#welcome"

  match 'bookmarklet' => "users#bookmarklet"
  post 'bookmark', :controller => :sources, :action => :create

  resources :sources do
    collection do
      get 'recent'
      get 'popular'
    end
  end

  resources :subscriptions do
    resources :sources
  end

  resources :users do
    resources :sources
    resources :subscriptions
  end

  resources :tags, only: [:show, :index]


  root :to => 'pages#home'

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/views/shared/_header.erb
<header class="navigation">
  <div class="menu-wrapper">
    <a href="/" class="logo">
      <img src="https://raw.github.com/Magnus-G/Random/master/placeholder_logo_1.png" alt="">
    </a>
    <p class="navigation-menu-button" id="js-mobile-menu">MENU</p>
    <div class="nav">
      <ul id="navigation-menu">
        <%- if current_user %>
          <li class="nav-link"><%= link_to "Listen", root_path %></li>
        <% end %>
        <li class="nav-link"><%= link_to "Recent", recent_sources_path %></li>
        <li class="nav-link"><%= link_to "Popular", popular_sources_path %></li>
        <li class="nav-link"><%= link_to "About", '/welcome' %></li>
        <li class="nav-link more"><a href="javascript:void(0)">More</a>
          <ul class="submenu">
            <li><%= link_to "Categories", categories_path %></li>
            <li><%= link_to "Tags", tags_path %></li>
          </ul>
        </li>

      </ul>
    </div>
    <div class="navigation-tools">
      <!--
      <div class="search-bar">
        <div class="search-and-submit">
          <input type="search" placeholder="Enter Search" />
          <button type="submit">
            <img src="https://raw.githubusercontent.com/Magnus-G/Random/master/search-icon.png" alt="">
          </button>
        </div>
      </div>
      -->
      <p>
        <% if current_user %>
          <%= link_to 'Sign out', destroy_user_session_path, :class => 'sign-in', :method => :delete %>
          <%= link_to 'Profile', current_user, :class => 'sign-up' %>
        <% else %>
          <%= link_to 'Sign up', new_registration_path(:user), :class => 'sign-up' %>
          <%= link_to 'Sign in', new_user_session_path, :class => 'sign-in' %>
        <% end %>
      </p>
    </div>
  </div>
</header>

<script>
  $(function() {
    var menu = $('#navigation-menu');
    var menuToggle = $('#js-mobile-menu');
    var signUp = $('.sign-up');

    $(menuToggle).on('click', function(e) {
      e.preventDefault();
      menu.slideToggle(function(){
        if(menu.is(':hidden')) {
          menu.removeAttr('style');
        }
      });
    });

    // underline under the active nav item
    $(".nav .nav-link").click(function() {
      $(".nav .nav-link").each(function() {
        $(this).removeClass("active-nav-item");
      });
      $(this).addClass("active-nav-item");
      $(".nav .more").removeClass("active-nav-item");
    });
  });
</script>

app/views/shared/_header.html.erb
<header class="navigation">
  <div class="menu-wrapper">
    <a href="/" class="logo">
      <%= icon 'volume-up' %>
      ListenLater
    </a>
    <p class="navigation-menu-button" id="js-mobile-menu">MENU</p>
    <div class="nav">
      <ul id="navigation-menu">
        <%- if current_user %>
          <li class="nav-link"><%= link_to "Listen", root_path %></li>
        <% end %>
        <li class="nav-link"><%= icon 'list-ul' %> <%= link_to "Play Queue", recent_sources_path %></li>
        <li class="nav-link"><%= icon 'folder-open-o' %> <%= link_to "Browse Categories", categories_path %></li>
        <li class="nav-link"><%= icon 'bookmark-o' %> <%= link_to "Get Bookmarklet", '/bookmarklet' %></li>
        <li class="nav-link more"><%= icon 'plus-square-o' %> <a href="javascript:void(0)">More</a>
          <ul class="submenu">
            <li><%= icon 'star' %> <%= link_to "Popular Series", popular_sources_path %></li>
            <li><%= icon 'tags' %> <%= link_to "Sort By Tags", tags_path %></li>
            <li><%= icon 'question' %> <%= link_to "About", '/welcome' %></li>
          </ul>
        </li>

      </ul>
    </div>
    <div class="navigation-tools">
      <!--
      <div class="search-bar">
        <div class="search-and-submit">
          <input type="search" placeholder="Enter Search" />
          <button type="submit">
            <img src="https://raw.githubusercontent.com/Magnus-G/Random/master/search-icon.png" alt="">
          </button>
        </div>
      </div>
      -->
      <p>
        <% if current_user %>
          <%= link_to 'Sign out', destroy_user_session_path, :class => 'sign-in' %>
          <%= link_to 'Profile', current_user, :class => 'sign-up' %>
        <% else %>
          <%= link_to 'Sign up', new_registration_path(:user), :class => 'sign-up' %>
          <%= link_to 'Sign in', new_user_session_path, :class => 'sign-in' %>
        <% end %>
      </p>
    </div>
  </div>
</header>

<script>
  $(function() {
    var menu = $('#navigation-menu');
    var menuToggle = $('#js-mobile-menu');
    var signUp = $('.sign-up');

    $(menuToggle).on('click', function(e) {
      e.preventDefault();
      menu.slideToggle(function(){
        if(menu.is(':hidden')) {
          menu.removeAttr('style');
        }
      });
    });

    // underline under the active nav item
    $(".nav .nav-link").click(function() {
      $(".nav .nav-link").each(function() {
        $(this).removeClass("active-nav-item");
      });
      $(this).addClass("active-nav-item");
      $(".nav .more").removeClass("active-nav-item");
    });
  });
</script>

app/views/shared/_header_haml.haml
= render 'refills/navigation'
-#%header.navigation
  -#.navigation-wrapper
    -#.container
      -#%a.logo = Rails.configuration.application_name
      -#%a.navigation-menu-button#js-mobile-menu
        -#MENU

      -#- if user_signed_in?
        -#.nav
          -#%ul#navigation-menu
            -#%li= link_to 'Recent', '/sources/recent'
            -#%li= link_to 'Popular', '/sources/popular'
          -#.navigation-tools
            -#%ul.nav
              -#%li= link_to current_user.email, edit_user_registration_path
              -#%li= link_to 'Sign out', destroy_user_session_path, :method => :delete
      -#- else
        -#.nav
          -#%ul#navigation-menu
            -#%li=link_to 'Sign in', new_user_session_path, :id => 'email_sign_in'
            -#%li=link_to 'Sign up',new_registration_path(:user)

app/views/shared/_side_nav.haml
%ul.nav.nav-list
  %li.nav-header Sources
  = render :partial => 'sources/nav'

  %li.nav-header Subscriptions
  = render :partial => 'subscriptions/nav'

  %li.nav-header Bookmarklet
  %li= link_to "Learn More", '/pages/bookmarklet'

app/views/shared/_side_nav.html.haml
%ul.nav.nav-list
  %li.nav-header Sources
  = render :partial => 'sources/nav'

  %li.nav-header Subscriptions
  = render :partial => 'subscriptions/nav'

  %li.nav-header Bookmarklet
  %li= link_to "Learn More", '/pages/bookmarklet'