config/routes.rb
ListenLater::Application.routes.draw do

  resources :series do
    resources :subscriptions, only: :create
    resources :sources, only: [:index, :show]
  end

  resources :categories, only: [:show, :index]
  resources :listens, only: [:create, :show]


  match '/', :controller => :pages, :action => :home
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    delete '/users/disconnect/:provider',
      :to => 'users#disconnect_omniauth_provider',
      :as => 'disconnect_omniauth_provider'
  end

  match 'welcome' => "users#welcome"

  match 'bookmarklet' => "users#bookmarklet"
  post 'bookmark', :controller => :sources, :action => :create

  resources :sources do
    collection do
      get 'recent'
      get 'popular'
    end
  end

  resources :subscriptions do
    resources :sources
  end

  resources :users do
    resources :sources
    resources :subscriptions
  end

  resources :tags, only: [:show, :index]


  root :to => 'pages#home'

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base

  belongs_to :series
  belongs_to :user
  has_many :sources, :through => :series

  def unlistened_source_count
    sources.count
  end

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  respond_to :json, :html

  def recent
    index
  end

  def popular
    index
  end

  def new
   @subscription = Subscription.new
  end

  def create
    @subscription = Subscription.new
    @subscription.series = Series.find(params[:series_id]) if params[:series_id].present?
    @subscription.series = Series.create(title: params[:title], url: params[:url]) if params[:url].present?
    @subscription.user = current_user
    @subscription.save!
    respond_with @subscription
  end

  def index
    @subscriptions = Subscription.all.includes(:series)
    respond_with @subscriptions
  end

  def show
    @subscription = Subscription.find(params[:id])
    respond_with @subscription
  end


end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_detail.erb
<div class="side-image">
  <div class="images-wrapper" style="background-image: url('<%= @subscription.image_url %>')"></div>
    <div class="content">
      <%- @subscription.tag_list.each do |tag| %>
        <h4><%= link_to tag, tag_path(:id => tag) %></h4>
      <% end %>
      <h1><%= @subscription.title %></h1>
      <p><%= @subscription.description %></p>
      <%= render 'filters' %>
  </div>
</div>

app/views/subscriptions/_form.haml
= simple_form_for @subscription do |form|
  = form.input :title
  = form.input :url, :hint => "RSS Feed Link - look for orange icon"
  = form.button :submit, :class => "btn-primary"

app/views/subscriptions/_list.html.erb
<ul class="subscription-list">
  <% @subscriptions.each do |subscription| %>
    <li class="subscription">
      <div class="subscription-image"><%= image_tag subscription.image_url %></div>
      <h2><%= link_to subscription.title, subscription %></h2>
      <h3><%= subscription.description %></h3>
    </li>
  <% end %>
</ul>

app/views/subscriptions/_subscription.haml
.subscription-list-item
  = image_tag subscription.image_url, class: 'subscription-image', height: 100, width: 'auto'
  %h2= link_to subscription.title, subscription_sources_path(subscription)

app/views/subscriptions/edit.haml
.hero-unit
  %h1
    Edit Subscription:
    = @subscription.title

= render 'form'

app/views/subscriptions/index.haml
%h1 Subscriptions
= link_to "Subscribe to New Audio", new_subscription_path, class: 'button'
= render partial: 'subscriptions/list'

= will_paginate @subscriptions

app/views/subscriptions/new.haml
.hero-unit
  %h1 New Subscription
  %p Keep up to date with fresh content pushed to you
= render 'form'

app/views/subscriptions/show.haml
.hero-unit
  %h1= @subscription.series.title
  %p #{@subscription.unlistened_source_count} New Sources of #{@subscription.sources.count}

= link_to "View Sources", series_sources_path(@subscription.series)