config/routes.rb
ListenLater::Application.routes.draw do

  resources :series do
    resources :subscriptions, only: :create
    resources :sources, only: [:index, :show]
  end

  resources :categories, only: [:show, :index]
  resources :listens, only: [:create, :show]


  match '/', :controller => :pages, :action => :home
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    delete '/users/disconnect/:provider',
      :to => 'users#disconnect_omniauth_provider',
      :as => 'disconnect_omniauth_provider'
  end

  match 'welcome' => "users#welcome"

  match 'bookmarklet' => "users#bookmarklet"
  post 'bookmark', :controller => :sources, :action => :create

  resources :sources do
    collection do
      get 'recent'
      get 'popular'
    end
  end

  resources :subscriptions do
    resources :sources
  end

  resources :users do
    resources :sources
    resources :subscriptions
  end

  resources :tags, only: [:show, :index]


  root :to => 'pages#home'

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  respond_to :json, :html

  def recent
    index
  end

  def popular
    index
  end

  def new
   @series = Series.new
  end

  def create
    @series = Series.new(params[:series])
    @series.save!
    #TODO
    # Background this
    @subscription = @series.subscriptions.create(:user => current_user).save if current_user
    respond_with @series
  end

  def index
    @series = Series.ordered.paginate({page: params[:page] || 1, per_page: params[:per_page] || 50})
    respond_with @series
  end

  def show
    @series = Series.find(params[:id], include: :sources)
    @sources = @series.sources.paginate({page: params[:page] || 1, per_page: params[:per_page] || 50})
    respond_with @series
  end

end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/series/_detail.html.erb
<div class="side-image">
  <div class="images-wrapper" style="background-image: url('<%= @series.image_url %>')"></div>
    <div class="content">
      <%- @series.tag_list.each do |tag| %>
        <h4><%= link_to tag, tag_path(:id => tag) %></h4>
      <% end %>
      <h1><%= @series.title %></h1>
      <p><%= @series.description %></p>
  </div>
</div>

app/views/series/_form.haml
= simple_form_for @series do |form|
  = form.input :title
  = form.input :url, :hint => "RSS Feed Link - look for orange icon"
  = form.button :submit, :class => "btn-primary"

app/views/series/_series.erb
<h2>
  <%= link_to series.title, series_sources_path(series) %>
  <%= link_to "Subscribe", series_subscriptions_path(series), :method => :post, :remote => true %>
</h2>

app/views/series/edit.haml
.hero-unit
  %h1
    Edit Series:
    = @series.title

= render 'form'

app/views/series/index.haml
%h1 Series
= render @series

= will_paginate @series

app/views/series/new.haml
.hero-unit
  %h1 New Series
  %p Keep up to date with fresh content pushed to you
= render 'form'

app/views/series/popular.haml
.hero-unit
  %h1 Popular
  %p Keep up

%ul
  = render @series

= will_paginate @series

app/views/series/recent.haml
.hero-unit
  %h1 Recent
  %p Keep up

%ul
  = render @series

= will_paginate @series

app/views/series/show.haml
= render 'series/detail' if @series

%ul.playlist
  = render @sources

= will_paginate @sources